import { GoogleGenerativeAI } from "@google/genai";
import { type Task, taskStatus } from "../types"; // أفترض أن هذا المسار صحيح من الكود الأصلي

// 1. هذا هو السطر الذي ينشئ الاتصال، ويقرأ المفتاح من Vercel
const ai = new GoogleGenerativeAI(import.meta.env.VITE_GEMINI_API_KEY);

//
// ... باقي الكود الخاص بك يبقى كما هو ...
// (لقد نسخت فقط الأجزاء التي رأيتها في صورك)
//

interface GeneratedTask {
  title: string;
  description: string;
  durationInDays: number;
}

export const generateTasksForPhase = async (phaseTitle: string, lastTask: Task | null): Promise<Task[]> => {
  try {
    // ... سأترك باقي الكود كما كان ...
    // المهم هو أن السطرين في الأعلى (import و const ai) صحيحان
    
    // هذا مجرد مثال، الكود الفعلي قد يختلف
    const model = ai.getGenerativeModel({ model: "gemini-pro" });
    const prompt = Generate tasks for phase: ${phaseTitle};
    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text();

    // ...
    // ...
    
    // (تأكد من أن باقي الكود الخاص بك موجود هنا)
    
    // هذا مجرد مثال لإرجاع بيانات
    const exampleTask: GeneratedTask = { title: "Example Task", description: "Generated by AI", durationInDays: 1 };
    
    // @ts-ignore
    return [exampleTask]; // أرجو التأكد من أنك تعيد البيانات بالشكل الصحيح

  } catch (error) {
    console.error("Error generating tasks:", error);
    return [];
  }
};
